#!/usr/bin/env bash
# playtest-sheet.sh [saturday YYYY-MM-DD] — print the weekly playtest sheet (Markdown) to stdout.
#
# Friday's /daily-standup writes the output to production/qa/playtests/playtest-<saturday>.md.
# The owner fills it on Saturday before 22:00 (~30 min); /weekly-wrapup reads it at 22:00.
# Sections: A fixed smoke list (tests/smoke/critical-paths.md), B bugs awaiting runtime confirmation,
# C what changed this week (non-chore commits on any branch, last 7 days). Read-only.
set -u
REPO="${REPO:-.}"
cd "$REPO" || exit 2
SAT="${1:-$(date -d 'next saturday' +%Y-%m-%d 2>/dev/null || date +%Y-%m-%d)}"
SMOKE="tests/smoke/critical-paths.md"

cat <<EOF
# Weekly Playtest — $SAT

> Generated by \`.claude/scripts/playtest-sheet.sh\` for the Saturday session (~30 min).
> Fill the **Result** column with \`PASS\`, \`FAIL\` or \`SKIP\`, and a short note on every FAIL.
> \`/weekly-wrapup\` reads this file at 22:00: every FAIL becomes a bug-inbox note.

| Field | Value |
|---|---|
| Tester | |
| Date / time played | |
| Build | Editor Play Mode from \`MainGamePlay\` (build index 0) |
| Branch / HEAD played | \`$(git rev-parse --abbrev-ref HEAD)\` / \`$(git rev-parse --short HEAD)\` at sheet generation — update if different |
| Session length (min) | |

## A. Fixed smoke list (~10 min)

| # | Step | Expected | Result | Note |
|---|---|---|---|---|
EOF
if [ -f "$SMOKE" ]; then
  grep -E '^\| *[0-9]+ *\|' "$SMOKE" | awk -F'|' '{printf "| %s | %s | %s | | |\n", $2, $3, $4}' | sed 's/  */ /g'
else
  echo "| — | \`$SMOKE\` missing | — | | |"
fi

cat <<'EOF'

## B. Bugs fixed in code, awaiting a runtime check (~10 min)

| Bug | Title | Fixed in | How to check | Result | Note |
|---|---|---|---|---|---|
EOF
found=0
rows=""
for f in production/qa/bugs/BUG-*.md; do
  st=$(grep -m1 -E '^\*\*Status\*\*' "$f" | sed -E 's/^\*\*Status\*\*:? *//')
  up=$(printf '%s' "$st" | tr '[:lower:]' '[:upper:]')
  # first status keyword decides (later text is usually history)
  first=$(printf '%s' "$up" | awk '{best="";bp=1e9;n=split("OPEN CLOSED ACCEPTED PARTIAL FIXED",k," ");
          for(i=1;i<=n;i++){p=index($0,k[i]); if(p>0&&p<bp){bp=p;best=k[i]}} print best}')
  case "$first" in
    PARTIAL) ;;
    FIXED) case "$up" in *CONFIRM*|*"PLAY MODE"*) ;; *) continue ;; esac ;;
    *) continue ;;
  esac
  id=$(basename "$f" .md)
  title=$(grep -m1 -E '^\*\*Title\*\*' "$f" | sed -E 's/^\*\*Title\*\*:? *//' | cut -c1-90 | tr '|' '/')
  fix=$(printf '%s' "$st" | grep -oE '`[0-9a-f]{7,40}`' | head -1)
  how=$(awk '/^## (Verify|Reproduction|Steps to Reproduce)/{f=1;next} f&&/^## /{exit} f&&NF{print; exit}' "$f" | cut -c1-90 | tr '|' '/')
  rows="$rows| $id | $title | ${fix:-—} | ${how:-see bug file} | | |"$'\n'
  found=$((found + 1))
done
# newest 8 only, so section B stays ~10 minutes
printf '%s' "$rows" | sort -r | head -8
[ $found -gt 8 ] && echo "| … | $((found - 8)) older fixed-but-unconfirmed bugs omitted | | | | |"
[ $found -eq 0 ] && echo "| — | none this week | — | — | | |"

cat <<'EOF'

## C. Changed this week — free play (~10 min)

Play these areas freely; note anything odd.

| Commit | Date | Summary | Result | Note |
|---|---|---|---|---|
EOF
git log --all --no-merges --since='7 days ago' --format='%h|%ad|%s' --date=short \
  | grep -viE '\|(chore|docs)(\(|:)|\|(index|WIP) on ' | head -15 \
  | awk -F'|' '{printf "| `%s` | %s | %s | | |\n", $1, $2, substr($3,1,80)}'

cat <<'EOF'

## D. Anything else noticed

-
EOF
